"""Position, team and franchise lookups.

Transcribed from ``R/recode_vars.R``.  ``pos_corrections`` and
``team_corrections`` normalise the many spellings the sources use before any
player-id matching happens.
"""

from __future__ import annotations

from .rcompat.stats import NamedVec

pos_corrections = NamedVec([
    ('Def', 'DST'),
    ('D', 'DST'),
    ('DEF', 'DST'),
    ('D/ST', 'DST'),
    ('PK', 'K'),
    ('CB', 'DB'),
    ('S', 'DB'),
    ('DE', 'DL'),
    ('DT', 'DL'),
    ('FS', 'DB'),
    ('ILB', 'LB'),
    ('OLB', 'LB'),
    ('SS', 'DB'),
    ('FB', 'RB'),
])

team_corrections = NamedVec([
    ('KCC', 'KC'),
    ('SFO', 'SF'),
    ('TBB', 'TB'),
    ('NEP', 'NE'),
    ('RAM', 'LAR'),
    ('LA', 'LAR'),
    ('SDC', 'LAC'),
    ('ARZ', 'ARI'),
    ('NOR', 'NO'),
    ('GBP', 'GB'),
    ('JAX', 'JAC'),
    ('WSH', 'WAS'),
    ('HST', 'HOU'),
    ('CLV', 'CLE'),
    ('BLT', 'BAL'),
    ('NWE', 'NE'),
    ('NOS', 'NO'),
    ('LVR', 'LV'),
    ('STL', 'LAR'),
    ('OAK', 'LV'),
    ('SD', 'LAC'),
])

nflTeam_abb = [
    'ARI',
    'ATL',
    'BAL',
    'BUF',
    'CAR',
    'CHI',
    'CIN',
    'CLE',
    'DAL',
    'DEN',
    'DET',
    'GB',
    'HOU',
    'IND',
    'JAC',
    'KC',
    'MIA',
    'MIN',
    'NO',
    'NE',
    'NYG',
    'NYJ',
    'PHI',
    'PIT',
    'LA',
    'SF',
    'LAC',
    'TB',
    'TEN',
    'WAS',
    'SEA',
    'LV',
]

nflTeam_id = [
    '100026',
    '100001',
    '100002',
    '100003',
    '100004',
    '100005',
    '100006',
    '100007',
    '100008',
    '100009',
    '100010',
    '100011',
    '100013',
    '100014',
    '100015',
    '100016',
    '100019',
    '100020',
    '100022',
    '100021',
    '100023',
    '100024',
    '100025',
    '100027',
    '100017',
    '100029',
    '100028',
    '100031',
    '100012',
    '100032',
    '100030',
    '100018',
]

nflTeam_city = [
    'Arizona',
    'Atlanta',
    'Baltimore',
    'Buffalo',
    'Carolina',
    'Chicago',
    'Cincinnati',
    'Cleveland',
    'Dallas',
    'Denver',
    'Detroit',
    'Green Bay',
    'Houston',
    'Indianapolis',
    'Jacksonville',
    'Kansas City',
    'Miami',
    'Minnesota',
    'New Orleans',
    'New England',
    'New York',
    'New York',
    'Philadelphia',
    'Pittsburgh',
    'Los Angeles',
    'San Francisco',
    'Los Angeles',
    'Tampa Bay',
    'Tennessee',
    'Washington',
    'Seattle',
    'Las Vegas',
]

nflTeam_name = [
    'Cardinals',
    'Falcons',
    'Ravens',
    'Bills',
    'Panthers',
    'Bears',
    'Bengals',
    'Browns',
    'Cowboys',
    'Broncos',
    'Lions',
    'Packers',
    'Texans',
    'Colts',
    'Jaguars',
    'Chiefs',
    'Dolphins',
    'Vikings',
    'Saints',
    'Patriots',
    'Giants',
    'Jets',
    'Eagles',
    'Steelers',
    'Rams',
    '49ers',
    'Chargers',
    'Buccaneers',
    'Titans',
    'Commanders',
    'Seahawks',
    'Raiders',
]

# R derives these from nflTeam_abb (R/recode_vars.R:19-20).  Note the second
# replacement tests the *original* vector, and that nflTeam_abb already spells
# Jacksonville "JAC", so only the Rams abbreviation actually changes.
mflTeam_abb = ["LAR" if abb == "LA" else ("JAC" if abb == "JAX" else abb) for abb in nflTeam_abb]

__all__ = [
    "pos_corrections",
    "team_corrections",
    "nflTeam_abb",
    "mflTeam_abb",
    "nflTeam_id",
    "nflTeam_city",
    "nflTeam_name",
]
